### ISSUE TITLE
Unable to push basic FITS file with NGAS QUARCHIVE: "Keyword 'ARCFILE' not found."

### ISSUE THREAD

**Issue by danjampro** [ICRAR/ngas#20] opened 2020-01-29 02:23 UTC
Hello,

I have a "working" NGAS server running but I am not able to push even a basic FITS file without error.

Code snippet (python):

```
import requests
with open('test.fits', 'rb') as f: 
    url = 'http://localhost:7778/QARCHIVE?filename=test.fits' 
    r = requests.post(url, data=f)
```

Result (server-side):

`KeyError: "Keyword 'ARCFILE' not found."`

This seems to be originating in the getDpIdInfo code in ngamsFitsPlugIn.py. I'm a little confused why this code should be running, as I have not read that an 'ARCFILE' key in the FITS header is required for NGAS and the NGAS filename (I thought) is specified in the http request.

Is this expected default behaviour? 

P.S. I tried to upload the FITS file but apparently it is not supported by GitHub... Let me know if you require it. It was generated along with its default header from scratch using astropy (I have also tried other FITS files, with the same result).

**Comment by rtobar** [comment] 2020-01-29 04:40
Hi @danjampro,

This is "expected" behavior in the sense that we know this is what the default FITS plugin does, but is of course unexpected for new users. I think this is mostly historical: when NGAS was originally developed at ESO, they wanted to have a FITS keyword to specify a filename, and use *that* as the final filename on storage. Note that because of this, in theory any plug-in can compute filenames in different ways, instead of relying in the `filename` HTTP parameter, which serves as the default.

There are a few ways to go around this: you can take a copy of the default FITS plug-in and modify it to *not* take into account the `ARCFILE` keyword, and use that plugin instead; you could also try to archive the file with `mime_type=application/octet-stream` which would work, but you'd loose the mime type information; or you could try to add a new parameter to the FITS plug-in to skip checking for the `ARCFILE` keyword and use the incoming `filename` instead as the name of the file on disk.

**Comment by danjampro** [comment] 2020-01-29 05:12
Hi @rtobar, thanks for your response.

I just successfully archived a file with octet-stream. Is there a way to preserve the mime type with this approach? It would be good to avoid creating our own fork of NGAS.

**Comment by rtobar** [comment] 2020-01-29 07:16
No, the `mime_type=application/octet-stream` simply forces NGAS to use a different plug-in, as plug-ins are fully mime-type-dependent. So yes, mime-types are fairly central to the operation of the server; not only are they used for picking a archiving plug-in, but storage can also be organized around mime types, plus other details.

To adjust for your use case (a very valid one!) I just added a new `ignore_arcfile` option for the FITS plug-in to ignore the `ARCFILE` keyword (off by default to preserve current behavior), could you give it a try? It's in the new `fits_optional_arcfile` branch. Adding an `ignore_arcfile=1` HTTP parameter should be enough to activate the functionality.

**Comment by danjampro** [comment] 2020-01-30 02:04
Hit @rtobar, thanks for adding this modification. I tested it with ignore_arcfile=1 but I get the error:

dc_ngas_cache_ | Traceback (most recent call last):
dc_ngas_cache_ |   File "/usr/local/lib/python3.7/site-packages/ngamsServer-11.0-py3.7.egg/ngamsServer/ngamsServer.py", line 1634, in reqCallBack
dc_ngas_cache_ |     method, path, headers)
dc_ngas_cache_ |   File "/usr/local/lib/python3.7/site-packages/ngamsServer-11.0-py3.7.egg/ngamsServer/ngamsServer.py", line 1728, in handleHttpRequest
dc_ngas_cache_ |     ngamsCmdHandling.handle_cmd(self, reqPropsObj, httpRef)
dc_ngas_cache_ |   File "/usr/local/lib/python3.7/site-packages/ngamsServer-11.0-py3.7.egg/ngamsServer/ngamsCmdHandling.py", line 63, in handle_cmd
dc_ngas_cache_ |     msg = _get_module(srvObj, reqPropsObj).handleCmd(srvObj, reqPropsObj, httpRef)
dc_ngas_cache_ |   File "/usr/local/lib/python3.7/site-packages/ngamsServer-11.0-py3.7.egg/ngamsServer/commands/qarchive.py", line 80, in handleCmd
dc_ngas_cache_ |     do_replication=False)
dc_ngas_cache_ |   File "/usr/local/lib/python3.7/site-packages/ngamsServer-11.0-py3.7.egg/ngamsServer/ngamsArchiveUtils.py", line 1033, in dataHandler
dc_ngas_cache_ |     do_replication=do_replication, transfer=transfer)
dc_ngas_cache_ |   File "/usr/local/lib/python3.7/site-packages/ngamsServer-11.0-py3.7.egg/ngamsServer/ngamsArchiveUtils.py", line 1168, in _dataHandler
dc_ngas_cache_ |     plugin_result = plugInMethod(srvObj, reqPropsObj)
dc_ngas_cache_ |   File "/usr/local/lib/python3.7/site-packages/ngamsPlugIns-11.0-py3.7.egg/ngamsPlugIns/ngamsFitsPlugIn.py", line 306, in ngamsFitsPlugIn
dc_ngas_cache_ |     uncomprSize, archFileSize, mime, compression, crc = compress(reqPropsObj, parDic)
dc_ngas_cache_ |   File "/usr/local/lib/python3.7/site-packages/ngamsPlugIns-11.0-py3.7.egg/ngamsPlugIns/ngamsFitsPlugIn.py", line 265, in compress
dc_ngas_cache_ |     return uncomprSize, archFileSize, mime, compression, crc
dc_ngas_cache_ | UnboundLocalError: local variable 'crc' referenced before assignment

**Comment by rtobar** [comment] 2020-01-30 04:08
Hi @danjampro, thanks for testing these changes. In fact you just hit a different error, this time related to the configuration of compression on the server-side. I again added a test to reproduce it, and also a patch to fix it. Would you mind pulling the latest changes from the `fits_optional_arcfile` branch and try again?

**Comment by danjampro** [comment] 2020-01-30 04:48
@rtobar I seem to have a talent for that! 

Just tried it and looks like it worked. Here is the response:

'<?xml version="1.0" ?>\n<!DOCTYPE NgamsStatus SYSTEM "http://91ba059e60a3:7777/RETRIEVE?internal=ngamsStatus.dtd">\n<NgamsStatus>\n  <Status Date="2020-01-30T04:45:32.056" HostId="91ba059e60a3:7777" Message="Successfully handled Archive Push Request for data file with URI: test.fits" RequestId="6c5ffce5-c476-45b1-87a1-0e6cd8c5500f" RequestTime="2020-01-30T04:45:30.194" State="ONLINE" Status="SUCCESS" SubState="IDLE" Version="11.0/2018-10-26T07:00:00"/>\n  <DiskStatus Archive="Data Central" AvailableMb="239654" BytesStored="100278720" Checksum="" Completed="0" CompletionDate="" DiskId="3c9d5032d0deffe1f94f566645f9861e" HostId="91ba059e60a3:7777" InstallationDate="2020-01-30T04:45:21.799" LastCheck="" LogicalName="BULK-M-000013" Manufacturer="0" MountPoint="/ngas/volumes/volume1" Mounted="1" NumberOfFiles="1" SlotId="volume1" TotalDiskWriteTime="1.6464760303497314" Type="None">\n    <FileStatus AccessDate="" Checksum="3481092114" ChecksumPlugIn="crc32" Compression="" ContainerId="None" CreationDate="2020-01-30T04:45:32.000" FileId="test.fits" FileName="Archive/2020-01-30/1/test.fits" FileSize="100278720" FileStatus="00000000" FileVersion="1" Format="image/x-fits" Group="" Ignore="0" IngestionDate="2020-01-30T04:45:32.026" IngestionRate="57089588" ModificationDate="" Owner="" Permissions="" Tag="" TotalIoTime="1.6464760303497314" UncompressedFileSize="100278720"/>\n  </DiskStatus>\n</NgamsStatus>'

Looks good to me - thanks a lot for your help, much appreciated.

**Comment by rtobar** [comment] 2020-01-30 06:21
@danjampro yes, I just did the merge so I'm closing this issue now.

**Closed by rtobar** 2020-01-30 06:21 UTC
Labels: enhancement
